/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legendaapp;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author ASUS
 */
public class InsertData extends javax.swing.JFrame {
    
    Connection connection;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form InsertData
     */
    public InsertData() {
        initComponents();
        findUsers();
    }
    
    public Connection getConnection()
    {
        Connection connection = null;
        
        try{
            connection = DriverManager.getConnection("jdbc:postgresql://localhost/Legenda?user=postgres&password=loader321");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return connection;
    }
    
    /**
     *
     * @return 
     */
 
    public ArrayList<User> ListUsers(String ValToSearch)
    {
        ArrayList<User> usersList = new ArrayList<User>();
        
        Statement st;
        ResultSet rs;
        
        try{
            Connection con = getConnection();
            st = con.createStatement();
            String searchQuery;
            searchQuery = "SELECT * FROM mahasiswa where CONCAT(id_mahasiswa, nama, jurusan, poin, gelar, semester) LIKE '%"+ValToSearch+"%'";
            rs = st.executeQuery(searchQuery);
            
            User user;
            
            while(rs.next())
            {
                user = new User(
                                 rs.getString("id_mahasiswa"),
                                 rs.getString("nama"),
                                 rs.getString("jurusan"),
                                 rs.getInt("poin"),
                                 rs.getString("gelar"),
                                 rs.getInt("semester"));
                
                usersList.add(user);
            }
            
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        
        return usersList;
    }
    /**
     *
     */
    
     public void findUsers()
    {
        ArrayList<User> users = ListUsers(jtextsearch.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"id_mahasiswa","nama","jurusan","poin","gelar","semester"});
        Object[] row = new Object[6];
        
        for(int i = 0; i < users.size(); i++)
        {
            row[0] = users.get(i).getNIM();
            row[1] = users.get(i).getNama();
            row[2] = users.get(i).getJurusan();
            row[3] = users.get(i).getPoin();
            row[4] = users.get(i).getGelar();
            row[5] = users.get(i).getSemester();
            model.addRow(row);
        }
       jtabelud.setModel(model);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtabelud = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jinsertsemesterd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jinsertnimd = new javax.swing.JTextField();
        jinsertnamad = new javax.swing.JTextField();
        jinsertpd = new javax.swing.JTextField();
        jinserttambah = new javax.swing.JButton();
        jinsertpoind = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jinserjurusan = new javax.swing.JTextField();
        jsearchd = new javax.swing.JButton();
        jtextsearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtabelud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_mahasiswa", "nama", "Jurusan", "poin", "gelar", "semester"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtabelud);

        jLabel5.setText("Semester");

        jLabel1.setText("id_mahasiswa");

        jinsertsemesterd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsertsemesterdActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        jLabel3.setText("Gelar");

        jLabel4.setText("POIN");

        jinsertnimd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsertnimdActionPerformed(evt);
            }
        });

        jinsertnamad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsertnamadActionPerformed(evt);
            }
        });

        jinserttambah.setText("Tambah");
        jinserttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinserttambahActionPerformed(evt);
            }
        });

        jLabel6.setText("Jurusan");

        jsearchd.setText("Search");

        jtextsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextsearchActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32)
                                .addComponent(jinsertsemesterd, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(54, 54, 54)
                                .addComponent(jinsertpoind, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 194, Short.MAX_VALUE)
                        .addComponent(jtextsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jsearchd)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jinserjurusan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(jinsertnamad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jinsertnimd, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jinsertpd, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jinserttambah))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jinsertnimd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jinsertnamad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jinserjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jsearchd)
                        .addComponent(jtextsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jinsertpoind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jinsertpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jinsertsemesterd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jinserttambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jinsertsemesterdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsertsemesterdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jinsertsemesterdActionPerformed

    private void jinsertnimdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsertnimdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jinsertnimdActionPerformed

    private void jinsertnamadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsertnamadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jinsertnamadActionPerformed

    private void jinserttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinserttambahActionPerformed
        findUsers();
        
        String jinsertpoin = jinsertpoind.getText();
        int insertpoin = Integer.valueOf(jinsertpoin);
        
         String jinsertsemester = jinsertsemesterd.getText();
         int jinsertsemesteri = Integer.valueOf(jinsertpoin);
        
        try{
            String sql = "INSERT INTO mahasiswa" + "(id_mahasiswa, nama, jurusan, poin, gelar, semester)" + "VALUES(?, ?, ?, ?, ?, ?)";

            connection = DriverManager.getConnection("jdbc:postgresql://localhost/Legenda?user=postgres&password=loader321");
            pst = connection.prepareStatement(sql);
            pst.setString(1, jinsertnimd.getText());
            pst.setString(2, jinsertnamad.getText());
            pst.setString(3, jinserjurusan.getText());
            pst.setInt(4, insertpoin);
            pst.setString(5, jinsertpd.getText());
            pst.setInt(6, jinsertsemesteri);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "sukses");

        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jinserttambahActionPerformed

    private void jtextsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextsearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                        PendisiplinForm pf = new PendisiplinForm();
                        pf.setVisible(true);
                        pf.pack();
                        pf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jinserjurusan;
    private javax.swing.JTextField jinsertnamad;
    private javax.swing.JTextField jinsertnimd;
    private javax.swing.JTextField jinsertpd;
    private javax.swing.JTextField jinsertpoind;
    private javax.swing.JTextField jinsertsemesterd;
    private javax.swing.JButton jinserttambah;
    private javax.swing.JButton jsearchd;
    private javax.swing.JTable jtabelud;
    private javax.swing.JTextField jtextsearch;
    // End of variables declaration//GEN-END:variables
}
