/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legendaapp;
import java.sql.*;
import javax.swing.*;


/**
 *
 * @author ASUS
 */
public class Loginasadmin extends javax.swing.JFrame {
String url = "jdbc:postgresql://localhost/Legenda?user=postgres&password=loader321";
ResultSet rs;
String sql = "SELECT * from login where id_username=? AND password=?";
PreparedStatement st;
    /**
     * Creates new form Loginasadmin
     */
    public Loginasadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlaausername = new javax.swing.JTextField();
        jlaapassword = new javax.swing.JPasswordField();
        jlaalogin = new javax.swing.JButton();
        jlaaback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Admin");

        jLabel2.setText("Password");

        jlaausername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlaausernameActionPerformed(evt);
            }
        });

        jlaalogin.setText("Login");
        jlaalogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlaaloginActionPerformed(evt);
            }
        });

        jlaaback.setText("Back");
        jlaaback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlaabackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlaausername, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jlaapassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jlaaback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(jlaalogin)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlaausername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlaapassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlaalogin)
                    .addComponent(jlaaback))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlaabackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlaabackActionPerformed
                    Login lo = new Login();
                    lo.setVisible(true);
                    lo.pack();
                    lo.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();                    this.dispose();    }//GEN-LAST:event_jlaabackActionPerformed

    private void jlaausernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlaausernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlaausernameActionPerformed

    private void jlaaloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlaaloginActionPerformed
            try {
                try (Connection connection = DriverManager.getConnection(url)) {
                    st = connection.prepareStatement(sql);
                    st.setString(1, jlaausername.getText());
                    st.setString(2, jlaapassword.getText());
                    rs = st.executeQuery();
                    if(rs.next()){
                        JOptionPane.showMessageDialog(null, "username and password matched");
                       
                        PendisiplinForm pf = new PendisiplinForm();
                        pf.setVisible(true);
                        pf.pack();
                        pf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                         this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "username and password unmatched");
                        jlaausername.setText("");
                        jlaapassword.setText("");
                    }
                }
             }
            catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

            }
    }//GEN-LAST:event_jlaaloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginasadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginasadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginasadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginasadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Loginasadmin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jlaaback;
    private javax.swing.JButton jlaalogin;
    private javax.swing.JPasswordField jlaapassword;
    private javax.swing.JTextField jlaausername;
    // End of variables declaration//GEN-END:variables
}
