/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legendaapp;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class UpdateData extends javax.swing.JFrame {
    Connection connection;
    PreparedStatement pst;
    ResultSet rs;
    
   
    public UpdateData() {
        initComponents();
    }
        public Connection getConnection()
    {
        Connection connection = null;
        
        try{
            connection = DriverManager.getConnection("jdbc:postgresql://localhost/Legenda?user=postgres&password=loader321");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return connection;
    }
    
    public ArrayList<Mahasiswa> ListUsers(String ValToSearch)
    {
        ArrayList<Mahasiswa> usersList = new ArrayList<Mahasiswa>();
        
        Statement st;
        ResultSet rs;
        
        try{
            Connection con = getConnection();
            st = con.createStatement();
            String searchQuery;
            searchQuery = "SELECT * FROM mahasiswa where CONCAT(id_mahasiswa, nama, pelanggaran, poin_dimasukkan, semester_pemasukkan) LIKE '%"+ValToSearch+"%'";
            rs = st.executeQuery(searchQuery);
            
            Mahasiswa user1;
            
            while(rs.next())
            {
                user1 = new Mahasiswa(
                                 rs.getString("id_mahasiswa"),
                                 rs.getString("nama"),
                                 rs.getString("pelanggaran"),
                                 rs.getInt("poin_dimasukkan"),
                                 rs.getInt("semester_pemasukan"));
                
                usersList.add(user1);
            }
            
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        
        return usersList;
    }
    
    // function to display data in jtable
    public void findUsers()
    {
        ArrayList<Mahasiswa> users = ListUsers(jinsertnim.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"NIM","NAMA","PELANGGARAN","POIN","semester"});
        Object[] row = new Object[5];
        
        for(int i = 0; i < users.size(); i++)
        {
            row[0] = users.get(i).getID();
            row[1] = users.get(i).getNAMA();
            row[2] = users.get(i).getPELANGGARAN();
            row[3] = users.get(i).getPOIN();
            row[4] = users.get(i).getSEMESTER();
            model.addRow(row);
        }
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jinserttambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jinsertnim = new javax.swing.JTextField();
        jinsertnama = new javax.swing.JTextField();
        jinsertp = new javax.swing.JTextField();
        jinsertpoin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jinsertsemester = new javax.swing.JTextField();
        jdelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jinserttambah.setText("Tambah");
        jinserttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinserttambahActionPerformed(evt);
            }
        });

        jLabel1.setText("NIM");

        jLabel2.setText("NAMA");

        jLabel3.setText("PELANGGARAN");

        jLabel4.setText("POIN");

        jinsertnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsertnimActionPerformed(evt);
            }
        });

        jinsertnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsertnamaActionPerformed(evt);
            }
        });

        jinsertpoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsertpoinActionPerformed(evt);
            }
        });

        jLabel5.setText("Semester");

        jinsertsemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsertsemesterActionPerformed(evt);
            }
        });

        jdelete.setText("Delete");
        jdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeleteActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jinsertpoin, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jinsertsemester))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jinsertp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(200, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jinsertnim, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jinsertnama, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jinserttambah)
                        .addGap(37, 37, 37)
                        .addComponent(jdelete)
                        .addGap(84, 84, 84))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jinsertnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jinsertnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jinsertp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jinsertpoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jinsertsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jinserttambah)
                    .addComponent(jdelete)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jinserttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinserttambahActionPerformed
        String jinsertpoinu = jinsertpoin.getText();
        int insertpoinu = Integer.valueOf(jinsertpoinu);
        
        String jinsertsemesterd = jinsertsemester.getText();
        int insertsemesteru = Integer.valueOf(jinsertsemesterd);
        try{
         String sql = "INSERT INTO insert_data" + "(id_mahasiswa, Nama, Pelanggaran, Poin_dimasukkan, Semester_Pemasukan)" + "VALUES(?, ?, ?, ?, ?)";
        
         connection = DriverManager.getConnection("jdbc:postgresql://localhost/Legenda?user=postgres&password=loader321");
         pst = connection.prepareStatement(sql);
         pst.setString(1, jinsertnim.getText());
         pst.setString(2, jinsertnama.getText());
         pst.setString(3, jinsertp.getText());
         pst.setInt(4, insertpoinu);
         pst.setInt(5, insertsemesteru);
         pst.executeUpdate();
         JOptionPane.showMessageDialog(null, "sukses");
         
         
     }catch (SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
    }//GEN-LAST:event_jinserttambahActionPerformed

    private void jinsertnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsertnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jinsertnimActionPerformed

    private void jinsertnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsertnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jinsertnamaActionPerformed

    private void jinsertsemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsertsemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jinsertsemesterActionPerformed

    private void jinsertpoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsertpoinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jinsertpoinActionPerformed

    private void jdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteActionPerformed
        try{
         String sql = "Delete From insert_data where id_mahasiswa =?";
         connection = DriverManager.getConnection("jdbc:postgresql://localhost/Legenda?user=postgres&password=loader321");
         pst = connection.prepareStatement(sql);
         pst.setString(1, jinsertnim.getText());
         pst.executeUpdate();
         JOptionPane.showMessageDialog(null, "sukses");
         
         
     }catch (SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }  
    }//GEN-LAST:event_jdeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                        PendisiplinForm pf = new PendisiplinForm();
                        pf.setVisible(true);
                        pf.pack();
                        pf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jdelete;
    private javax.swing.JTextField jinsertnama;
    private javax.swing.JTextField jinsertnim;
    private javax.swing.JTextField jinsertp;
    private javax.swing.JTextField jinsertpoin;
    private javax.swing.JTextField jinsertsemester;
    private javax.swing.JButton jinserttambah;
    // End of variables declaration//GEN-END:variables
}
